name: Build Windows Version
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'
    - name: Install dependencies
      run: |
        pip install pyinstaller send2trash requests
    - name: Build with PyInstaller
      run: |
        python -m PyInstaller --windowed --noconsole --onefile --name "DuplicateDeleter" DuplicateDeleter.py
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DuplicateDeleter-Windows
        path: dist/DuplicateDeleter.exe
