name: Build Windows Version v3.0.0
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'
    - name: Install dependencies
      run: |
        pip install pyinstaller send2trash requests pystray pillow
    - name: Build with PyInstaller
      run: |
        python -m PyInstaller --windowed --noconsole --onefile --name "DuplicateDeleter" DuplicateDeleter_v3.0.0.py
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DuplicateDeleter-Windows-v3.0.0
        path: dist/DuplicateDeleter.exe
